export default {

  CREATE_TASK: "CREATE_TASK",
  CREATE_TASK_REQUEST: "CREATE_TASK_REQUEST",
  CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS",
  CREATE_TASK_FAILURE: "CREATE_TASK_FAILURE",

  UPDATE_TASK: "UPDATE_TASK",
  UPDATE_TASK_REQUEST: "UPDATE_TASK_REQUEST",
  UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",
  UPDATE_TASK_FAILURE: "UPDATE_TASK_FAILURE",

  DELETE_TASK: "DELETE_TASK",
  DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
  DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
  DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE",

  COMPLETE_TASK: "COMPLETE_TASK",
  COMPLETE_TASK_REQUEST: "COMPLETE_TASK_REQUEST",
  COMPLETE_TASK_SUCCESS: "COMPLETE_TASK_SUCCESS",
  COMPLETE_TASK_FAILURE: "COMPLETE_TASK_FAILURE",

  SEARCH_TASK: "SEARCH_TASK",
  SEARCH_TASK_REQUEST: "SEARCH_TASK_REQUEST",
  SEARCH_TASK_SUCCESS: "SEARCH_TASK_SUCCESS",
  SEARCH_TASK_FAILURE: "SEARCH_TASK_FAILURE",

};
